<?php

namespace WCS\GotBundle\Repository;

/**
 * RoyaumeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoyaumeRepository extends \Doctrine\ORM\EntityRepository
{
}
